### ISSUE TITLE
样例报错

### ISSUE THREAD

**Issue by xsyl1124** [aeraki-framework/dubbo2istio#15]
istio 版本 1.10.0

aeraki 日志
...
2021-08-02T11:10:03.465916Z     warn    adsc    Error adding a new resource to the store 2 errors occurred:
        * service entry port 53 already defined
        * unsupported protocol: UnsupportedProtocol
..
dubbo2istio 日志正常
dubbo-sample-consumer 日志
Caused by: java.net.UnknownHostException: org.apache.dubbo.samples.basic.api.demoservice
        at java.net.InetAddress.getAllByName0(InetAddress.java:1281)
        at java.net.InetAddress.getAllByName(InetAddress.java:1193)
        at java.net.InetAddress.getAllByName(InetAddress.java:1127)
        at java.net.InetAddress.getByName(InetAddress.java:1077)
        at io.netty.util.internal.SocketUtils$8.run(SocketUtils.java:156)
        at io.netty.util.internal.SocketUtils$8.run(SocketUtils.java:153)
        at java.security.AccessController.doPrivileged(Native Method)
        at io.netty.util.internal.SocketUtils.addressByName(SocketUtils.java:153)
        at io.netty.resolver.DefaultNameResolver.doResolve(DefaultNameResolver.java:41)
        at io.netty.resolver.SimpleNameResolver.resolve(SimpleNameResolver.java:61)
        at io.netty.resolver.SimpleNameResolver.resolve(SimpleNameResolver.java:53)
        at io.netty.resolver.InetSocketAddressResolver.doResolve(InetSocketAddressResolver.java:55)
        at io.netty.resolver.InetSocketAddressResolver.doResolve(InetSocketAddressResolver.java:31)
        at io.netty.resolver.AbstractAddressResolver.resolve(AbstractAddressResolver.java:106)
        at io.netty.bootstrap.Bootstrap.doResolveAndConnect0(Bootstrap.java:206)
        at io.netty.bootstrap.Bootstrap.access$000(Bootstrap.java:46)

**以下是集群的信息：**
[root@k8s-master-201 ~]# kubectl get pods -n istio-system 
NAME                                    READY   STATUS    RESTARTS   AGE
aeraki-6558dcc746-95tk9                 1/1     Running   0          58m
istio-egressgateway-55d4df6c6b-cdbx8    1/1     Running   0          62m
istio-ingressgateway-69dc4765b4-wgrg2   1/1     Running   0          62m
istiod-798c47d594-p246k                 1/1     Running   0          62m
[root@k8s-master-201 ~]# 
[root@k8s-master-201 ~]# kubectl get pods -n dubbo 
NAME                                        READY   STATUS    RESTARTS   AGE
dubbo-sample-consumer-5778c77995-l7dr9      2/2     Running   0          50m
dubbo-sample-provider-v1-d5668f85c-jjnwg    2/2     Running   0          50m
dubbo-sample-provider-v2-65995864f6-xh9zw   2/2     Running   0          50m
dubbo2istio-7488477bd4-f4ngb                2/2     Running   0          49m
zookeeper-5dbc74b5db-l28q5                  2/2     Running   0          54m
[root@k8s-master-201 ~]# kubectl get se -n dubbo 
NAME                                                                     HOSTS                                                                 LOCATION        RESOLUTION   AGE
aeraki-org-apache-dubbo-samples-basic-api-complexservice-product-2-0-0   ["org.apache.dubbo.samples.basic.api.complexservice-product-2-0-0"]   MESH_INTERNAL   STATIC       48m
aeraki-org-apache-dubbo-samples-basic-api-complexservice-test-1-0-0      ["org.apache.dubbo.samples.basic.api.complexservice-test-1-0-0"]      MESH_INTERNAL   STATIC       48m
aeraki-org-apache-dubbo-samples-basic-api-demoservice                    ["org.apache.dubbo.samples.basic.api.demoservice"]                    MESH_INTERNAL   STATIC       48m
aeraki-org-apache-dubbo-samples-basic-api-testservice                    ["org.apache.dubbo.samples.basic.api.testservice"]                    MESH_INTERNAL   STATIC       48m
[root@k8s-master-201 ~]# 
[root@k8s-master-201 ~]# 
[root@k8s-master-201 ~]# kubectl get vs -n dubbo   
NAME               GATEWAYS   HOSTS                                                AGE
test-dubbo-route              ["org.apache.dubbo.samples.basic.api.demoservice"]   45m
[root@k8s-master-201 ~]# 
[root@k8s-master-201 ~]# 
[root@k8s-master-201 ~]# kubectl get dr -n dubbo   
NAME                         HOST                                             AGE
dubbo-circuit-breaker-rule   org.apache.dubbo.samples.basic.api.demoservice   45m
dubbo-sample-provider        org.apache.dubbo.samples.basic.api.demoservice   45m
[root@k8s-master-201 ~]#

**Comment by brucelwl** [comment]
我运行这个示例出现了同样的错误

**Comment by ccwxl** [comment]
> 我运行这个示例出现了同样的错误

有解决吗?

**Comment by brucelwl** [comment]
> > 我运行这个示例出现了同样的错误
> 
> 有解决吗?

按照这个解决 https://github.com/aeraki-framework/aeraki/issues/91
